### ISSUE TITLE
Publish Messages from file

### ISSUE THREAD

**Issue by maheshmahadevaiah** [pnopjp/jmeter-plugins#10]
Dear Team, I have download Service Bus extension and integrated with JMeter.
I would like to know, how can we publish messages by reading file. Message contains body and user properties.
Our use case demands publishing 10000 messages for one hour. Or publish 1/2/4/5 message per second.
Kindly support me.

**Comment by kuniteru** [comment]
Hi maheshmahadevaiah,

Do you want to know how to use the Service Bus extension?
Here is a tutorial for it, could you please read this first?
https://blog.pnop.co.jp/jmeter-azure-service-bus_en/

**Comment by maheshmahadevaiah** [comment]
Hi Kuniteru, I was able to publish messages to ServiceBus from above article.
My use-case is to publish message by reading a file and control the flow by sending 1/2/4/5 messages per second.
Just guide me how to make use of your extension to implement above use-case.

**Comment by kuniteru** [comment]
How about reading messages from a file using the [CSV Data Set Configuration Element](https://jmeter.apache.org/usermanual/component_reference.html#CSV_Data_Set_Config), [_CSVRead function](https://jmeter.apache.org/usermanual/functions.html#__CSVRead), [_StringFromFile function](https://jmeter.apache.org/usermanual/functions.html#__StringFromFile), etc.?
It can be used in the same way as it is used for HTTP requests.

**Comment by gbroner2000** [comment]
I'm not a part of this request, but it seem like a simple JMeter usage issue rather than a valid request. Might be wise to close.

**Comment by kuniteru** [comment]
Thanks, @gbroner2000
As you said, I think this is a simple JMeter usage issue, so I close this.
