### ISSUE TITLE
resource not configurable

### ISSUE THREAD

**Issue by SlateyDev** [pnopjp/jmeter-plugins#2]
https://github.com/pnopjp/jmeter-plugins/blob/790d534d31273699bc794f00031c020f056016c7/plugins/functions/src/main/java/jp/co/pnop/jmeter/functions/AzAdAccessToken.java#L92

resource needs to be separately configurable from clientId as when making requests to an API the authorization may be provided by a separate resource from that which allows the web site login.

**Comment by kuniteru** [comment]
@SlateyTV Thank you!

**Comment by SlateyDev** [comment]
Have tested the change in our environment and works great. Thanks for the prompt fix.
