### ISSUE TITLE
Clarifications for ENTRA ID Authentication Environment Variable

### ISSUE THREAD

**Issue by MissaouiChedy** [pnopjp/jmeter-plugins#26]
[In the documentation,](https://github.com/pnopjp/jmeter-plugins/blob/master/docs/samplers.md#parameters) it is specified that we can use entra id authentication when using the [Azure Event Hubs Sampler.](https://github.com/pnopjp/jmeter-plugins/blob/master/docs/samplers.md#azure-event-hubs)

However, sampler is requiring an environment variable containing entra id configuration details.

Unfortunately, it is not clear what the environment variable should contain, the tenant id ? the client id ?

@kuniteru  @dislev  @MalachiMcIntosh  Can you please clarify how to specify the environment variable ?

**I will be glad to contribute back your clarifications to the documentation.**

**Comment by kuniteru** [comment]
Hi @MissaouiChedy ,

Please see this page.
https://github.com/pnopjp/jmeter-plugins/blob/master/docs/configurations.md#microsoft-entra-id-credential

**Comment by MissaouiChedy** [comment]
Thank you @kuniteru, now I understand that it is a Jmeter variable and not an Environment Variable.
