### ISSUE TITLE
Custom properties

### ISSUE THREAD

**Issue by Jmeteruser** [pnopjp/jmeter-plugins#7]
Hi, Our application’s topic has SQL filter enabled which requires a custom property to be attached to the servicebusmessage, currently the plug-in doesn’t support this. Is there a way we can add user properties to the message ? Appreciate any help on this thanks

**Comment by kuniteru** [comment]
I have added the ability to send custom properties as well in the version we just released.
Please download and use the latest version.

**Comment by Jmeteruser** [comment]
that works perfect! I can confirm that I can add custom properties and see the messages successfully reaching the desired topic which has SQL filter enabled. Thanks for your quick help
